### ISSUE TITLE
"Price per"? 

### ISSUE THREAD

**Issue by vitalii2011** [yumi-modding/FS19_additionalFieldInfo#10]
Why is there such a large amount in "Price per"? What exactly does it show?

**Comment by dbump** [comment]
The price of fields is determined by the total land area, not just the smaller portion of that area that is defined by the field itself.  Some maps have very large areas with a tiny field, like the one shown in your screenshot.  The Price per section is calculating the cost per hectare/acre of just the arable field itself, for comparative use.

**Comment by vitalii2011** [comment]
Thanks a lot for the clarification. All clear.

**Comment by vitalii2011** [comment]
P.S. Misunderstanding arose because of "$/ha", better just "$". Probably better: "Price after free area processing"(ru.: "После обработки св. земли").
