### ISSUE TITLE
Yield Potential isn't working correctly.

### ISSUE THREAD

**Issue by stargatefreak** [yumi-modding/FS19_additionalFieldInfo#11]
I have run a few tests with this and the Yield potential doesn't work out the potential correctly.

I have used [Easy Development Controls](https://www.farming-simulator.com/mod.php?mod_id=138864) to manipulate a field.

When a field is absolutely perfect with the field has been ploughed, limed, weeded and fully fertilized the number is lower than when it has been neglected.

When a has-been neglected it will show a really high yield potential.

**Comment by yumi-modding** [comment]
Hello @stargatefreak,
I'm working on a new mod and in this context I noticed also this issue by using Easy Development Controls.
Actually the mod is using the computation made for the contract missions. But doing several missions recently I noticed how often you get extra material at the end of the mission.
I need to check how I could improve these numbers.
Thanks for the feedback

**Comment by yumi-modding** [comment]
Cf. #12 that is also related

**Comment by babarsc** [comment]
I'm not super familiar with lua or modding FS19, but I did look at your code and saw where the yield multiplier is being calculated.  I _think_ you're calling a function provided by the API.

I ran some experiments and found what's causing the errors.  

In summary, the logic is reversed when adding the multipliers for weeds, lime, and plow (but not fertilizer, that's correct).

According to my experiments, the multiplier are all additive despite the in game descriptions.  For example the in-game yield for wheat is 0.89L/m2 for a field that's had nothing done to it (needs lime, plowed, 0% fertilizer, and 100% weeds).   Each extra step to growing crops adds to the multiplier.  Fertilizing twice adds 0.5, (0.25 * 2), weeding adds 0.2, lime adds 0.15, and plowing adds 0.15.  This all adds up for a maximum multiplier of 2.  So a fully processed wheat field will yield 1.78 l/m2.  

I don't know what the data types are for `needsPlowFactor`, `needsLimeFactor` or `weedFactor` but the name suggests they'd all be 0 or false if the work for those steps was done, while `fertilizerFactor` would be true or some number if the field was fertilized. 

The addon gives a multiplier of 2 when the following conditions are met:

* 100% Fertilized (good)
* 100% weeds (bad)
* NOT plowed (bad)
* NO lime added (bad)

So to correct this, the 10% you added needs to be removed, and the logic for lime, plow, and weeds needs to be inverted.

**Comment by yumi-modding** [comment]
Hello @babarsc Thanks for the comment, I think you're right and I guess that what I did on FS22 version of the mod is correct compared to here. I don't play anymore on FS19 but i'll try to take some time to finally fix this issue since I think you're not the only one keeping using the mod.

**Comment by babarsc** [comment]
@yumi-modding thanks for getting back and I look forward to the fix.  

I play FS19 because it's part of Xbox Game Pass, FS22 isn't.  That's probably going to keep some of the FS19 mods in use for a while until FS22 comes to it. 

Thanks again.

**Comment by Nekzuris** [comment]
> I'm not super familiar with lua or modding FS19, but I did look at your code and saw where the yield multiplier is being calculated. I _think_ you're calling a function provided by the API.
> 
> I ran some experiments and found what's causing the errors.
> 
> In summary, the logic is reversed when adding the multipliers for weeds, lime, and plow (but not fertilizer, that's correct).
> 
> According to my experiments, the multiplier are all additive despite the in game descriptions. For example the in-game yield for wheat is 0.89L/m2 for a field that's had nothing done to it (needs lime, plowed, 0% fertilizer, and 100% weeds). Each extra step to growing crops adds to the multiplier. Fertilizing twice adds 0.5, (0.25 * 2), weeding adds 0.2, lime adds 0.15, and plowing adds 0.15. This all adds up for a maximum multiplier of 2. So a fully processed wheat field will yield 1.78 l/m2.
> 
> I don't know what the data types are for `needsPlowFactor`, `needsLimeFactor` or `weedFactor` but the name suggests they'd all be 0 or false if the work for those steps was done, while `fertilizerFactor` would be true or some number if the field was fertilized.
> 
> The addon gives a multiplier of 2 when the following conditions are met:
> 
>     * 100% Fertilized (good)
> 
>     * 100% weeds (bad)
> 
>     * NOT plowed (bad)
> 
>     * NO lime added (bad)
> 
> 
> So to correct this, the 10% you added needs to be removed, and the logic for lime, plow, and weeds needs to be inverted.

That's exactly what I also found, I've submitted a pull request with the fix.

**Comment by Nekzuris** [comment]
Also I found another smaller issue with the yield display, if you go on a sowed field and after go to a clear field (plowed or cultivated) the crop from the previous field is kept and yield calculation is displayed for the empty field.

I think it's because `self.fruitType` isn't cleared but I couldn't find where to do it, so I added a check to display the info only if `data.plowFactor == 0 and data.cultivatorFactor == 0`

And I think the info should be display as soon as the field is sowed, so you just need to remove the first check for `minHarvestingGrowthState`

Tell me if you want to fix it yourself or I can PR my change.

**Comment by yumi-modding** [comment]
Thanks for the comments, i was not aware of this bug. I'll try to have a look this week.
For the minHarvestingGrowthState, this was the intent to only display the value when the field is ready to harvest.
