### ISSUE TITLE
Precision Farming DLC

### ISSUE THREAD

**Issue by shaqFS** [yumi-modding/FS19_additionalFieldInfo#12]
Hi,
Is there a chance to adapt the mod to Precision Farming DLC?

best regards

shaq

**Comment by yumi-modding** [comment]
Hello,

Yes I've tested today more in detail Precision Farming and clearly I need to adapt my mod at least to avoid display glitch and certainly remove redondant information in case Precision Farming is loaded.
Thx for the issue

**Comment by Vanquish081** [comment]
Are you fixing the bug or adding more features?
