### ISSUE TITLE
Minor incompatibility with Info Menu mod. 

### ISSUE THREAD

**Issue by vitalii2011** [yumi-modding/FS19_additionalFieldInfo#14]
In the map overview, the line of information "Area" intersects with "Field" from the Info Menu v1.2 mod https://www.modhoster.com/mods/info-menu .
https://i.imgur.com/dUOt98u.png https://i.imgur.com/ggyYSJX.png

**Comment by yumi-modding** [comment]
Hello
Thanks for the feedback. I don't know this mod but I see the info seems redundant here. I can hide Area info if Info Menu mod is loaded

**Comment by vitalii2011** [comment]
Probably this will be the simplest and most elegant solution. )

**Comment by yumi-modding** [comment]
https://github.com/yumi-modding/FS19_additionalFieldInfo/blob/master/FS19_additionalFieldInfo.zip?raw=true should fix your issue
