### ISSUE TITLE
Will additionalFieldInfo also be available in FS22?

### ISSUE THREAD

**Issue by regs1980** [yumi-modding/FS19_additionalFieldInfo#15]
Will additionalFieldInfo also be available in FS22?

**Comment by yumi-modding** [comment]
Hello @regs1980 , yes a first version has been pushed to modhub but Giants told me to wait for next patch before validating it.
Wait and see

**Comment by regs1980** [comment]
Update 1.2.0.0 is out

**Comment by yumi-modding** [comment]
Thanks, i downloaded it. I will submit again to modhub
