### ISSUE TITLE
"False" error msg

### ISSUE THREAD

**Issue by ebelbeb** [yumi-modding/FS19_additionalFieldInfo#17]
Hi, I love Your work :) 

Sixth line in the additionalFieldInfo.lua file:
function AdditionalFieldInfo:loadedMission() --[[----------------------------------------------------------------]] print("This is a development version of AdditionalFieldInfo for FS22, which may and will contain errors, bugs.") end

Just a small suggestion not to use the word "error" in this type of message. I have a script that reports the word "error" in log.txt and I get a false alarm every time I start the game :)

**Comment by yumi-modding** [comment]
Hello @ebelbeb 
Thanks. Yes you're right and you could notice that the message is only on the github code, not on modhub.
Anyway, I will change it when i need to commit some new code.

**Comment by ebelbeb** [comment]
Err... This is also on ModHub :)
![image](https://user-images.githubusercontent.com/69918710/171032559-17b1571f-6734-428e-8fb5-a590cc9738ab.png)

**Comment by yumi-modding** [comment]
Oups, it looks like Giants validated the update a bit too fast.
Thanks I'll push the changes

**Comment by yumi-modding** [comment]
Oups, it looks like Giants validated the update a bit too fast.
Thanks I've push the changes to modhub
