### ISSUE TITLE
More of a question... 

### ISSUE THREAD

**Issue by Oak7603** [yumi-modding/FS19_additionalFieldInfo#9]
How do you change the refresh rate? The fields text skips by so fast that I can hardly see which field I'm looking for and by the time I see the field number I can't see the info before it has changed again.

**Comment by yumi-modding** [comment]
Hello,
Actually the refresh is directly link to the panel refresh event. Maybe it depends on fps I don't really know.
Actually I play generally on maps with 1 field per land so no issue.
I'll try to make some tests and maybe refresh the text only one on two.

**Comment by Oak7603** [comment]
No worries. Thanks for the speedy response. I'll keep an eye out for any updates :D

**Comment by yumi-modding** [comment]
Hello,
Please let me know if it's OK with this fix (last zip here https://github.com/yumi-modding/FS19_additionalFieldInfo/blob/master/FS19_additionalFieldInfo.zip)

**Comment by Oak7603** [comment]
Excellent stuff. Much better.

I am playing on Charwell which has fields grouped in parcels so the field text was cycling too quickly. This is just right.

Excellent and very prompt work 😊
